version: '3.8'

services:
  app:
    build: .
    container_name: fm_app_legal_os
    restart: always
    ports:
      - "80:80"
    volumes:
      - fm_data:/var/www/html/data
      - fm_uploads:/var/www/html/uploads
    environment:
      - DB_PATH=/var/www/html/data/database.sqlite

volumes:
  fm_data:
  fm_uploads:
